### ISSUE TITLE
create kwarg does not seem to be respected

### ISSUE THREAD

**Issue by disberd** [tecosaur/BaseDirs.jl#5]
I was trying to use this package to organize my files but the `create` kwarg (tested specifically for `BaseDirs.User.data` does not seem to work.

The following code does return false for me both in Linux and Windows:
```
BaseDirs.User.data("test"; create=true) |> isdir
```

**Comment by disberd** [comment]
Ok I just realized that the command above creates a file and not a directory and for that reason it returns false. Doing `BaseDirs.User.data("test/"; create=true) works

**Comment by tecosaur** [comment]
I'm about to update the docstrings to make this clearer:

```
 •  create::Bool (default false), whether the path should be created if it does not exist. Paths ending
    in / are interpreted as directories, and all other paths are considered files. This takes care to
    create the base directories with the appropriate permissions (700).
```
